### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by MrNico98** [Crunchy-DL/Crunchy-Downloader#28] opened 2024-07-02 18:20 UTC
![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/136261932/0f357b78-9628-400d-b451-bb99ad3847db)

**Comment by Elwador** [comment] 2024-07-03 07:23
it says what the problem is and without more context i can't help you

**Comment by Elwador** [comment] 2024-07-12 11:06
since you didn't reply i will close this issue

**Closed by Elwador** 2024-07-12 11:06 UTC
Labels: question
